webtalk_init -webtalk_dir /home/jxu48/research/riscv32/src/fpu_src/FPU/FPU.sim/sim_1/behav/xsim/xsim.dir/fp_top_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov 16 14:22:58 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210769129_1777527718_210710220_004" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "89ec635a-4b6d-4297-bf83-660b8e5a3dff" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8b276f56865043e2b299f678c406824b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "RedHatEnterpriseServer" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Red Hat Enterprise Linux Server release 7.9 (Maipo)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2404.809 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "51 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125532_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1346984415 -regid "210769129_1777527718_210710220_004" -xml /home/jxu48/research/riscv32/src/fpu_src/FPU/FPU.sim/sim_1/behav/xsim/xsim.dir/fp_top_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/jxu48/research/riscv32/src/fpu_src/FPU/FPU.sim/sim_1/behav/xsim/xsim.dir/fp_top_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/jxu48/research/riscv32/src/fpu_src/FPU/FPU.sim/sim_1/behav/xsim/xsim.dir/fp_top_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
