webtalk_init -webtalk_dir /home/tfowler6/riscv32/src/fpu_src/FPU/FPU.sim/sim_1/behav/xsim/xsim.dir/float_to_int_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov  5 11:33:02 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210769129_1777527718_210710220_004" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "43c60cc1-7122-4f94-8d78-1ffbc881a8ba" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8b276f56865043e2b299f678c406824b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "RedHatEnterpriseServer" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Red Hat Enterprise Linux Server release 7.9 (Maipo)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel Xeon Processor (Skylake, IBRS)" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394.374 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "7" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "19.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "3" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "23 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "3 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "26" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.42_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "378244_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3796349442 -regid "210769129_1777527718_210710220_004" -xml /home/tfowler6/riscv32/src/fpu_src/FPU/FPU.sim/sim_1/behav/xsim/xsim.dir/float_to_int_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/tfowler6/riscv32/src/fpu_src/FPU/FPU.sim/sim_1/behav/xsim/xsim.dir/float_to_int_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/tfowler6/riscv32/src/fpu_src/FPU/FPU.sim/sim_1/behav/xsim/xsim.dir/float_to_int_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
